services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urlshort
      MYSQL_USER: user
      MYSQL_PASSWORD: cet.123$
    ports:
    - "3306:3306"
    volumes:
    - ~/.mariadb_data:/var/lib/mysql
    restart: unless-stopped